# Generated by Django 2.0.5 on 2018-05-17 08:13

from django.db import migrations, models
import django.db.models.deletion


def create_initial_contact(apps, schema_editor):
    Model = apps.get_model('vvt', 'Department')
    Model(name="NOCH OFFEN", pk=1).save()
    Model = apps.get_model('vvt', 'Contact')
    Model(name="NOCH OFFEN", department=1, pk=1).save()

def create_person_categories(apps, schema_editor):
    Model = apps.get_model('vvt', 'PersonCategory')
    Model(name="ALLE").save()
    Model(name="Mitarbeiter").save()
    Model(name="Lieferanten").save()
    Model(name="Kunden").save()
    Model(name="Interessenten").save()


def create_data_categories(apps, schema_editor):
    Model = apps.get_model('vvt', 'DataCategory')
    Model(name="ALLE").save()
    Model(name="Name").save()
    Model(name="Adressdaten").save()
    Model(name="Kontaktdaten").save()
    Model(name="Organisatorische Zuordnung").save()


def create_recipient_categories(apps, schema_editor):
    Model = apps.get_model('vvt', 'RecipientCategory')
    Model(name="Mitarbeiter").save()
    Model(name="Abteilungsleitung").save()
    Model(name="Geschäftsführung").save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Contact')),
                ('email', models.CharField(blank=True, max_length=50, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Phone')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='DataCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Categories of personal data')),
            ],
            options={
                'verbose_name': 'Data Category',
                'verbose_name_plural': 'Data Categories',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Department')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='PersonCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Category of affected individuals')),
            ],
            options={
                'verbose_name': 'Person Category',
                'verbose_name_plural': 'Person Categories',
            },
        ),
        migrations.CreateModel(
            name='ProcessingActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Processing Activity')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Created on')),
                ('changed', models.DateField(auto_now=True, verbose_name='Changed on')),
                ('reason', models.TextField(verbose_name='Reason')),
                ('transfer', models.TextField(verbose_name='Transfer to third countries')),
                ('transfer_warrant', models.TextField(verbose_name='Transfer warrant')),
                ('retention', models.CharField(max_length=200, verbose_name='Retention period')),
                ('processors', models.TextField(verbose_name='Order processors')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vvt.Contact', verbose_name='Department')),
                ('data_categories', models.ManyToManyField(to='vvt.DataCategory', verbose_name='Categories of personal data')),
                ('person_categories', models.ManyToManyField(to='vvt.PersonCategory', verbose_name='Categories of affected individuals')),
            ],
            options={
                'verbose_name': 'Processing Activity',
                'verbose_name_plural': 'Processing Activities',
            },
        ),
        migrations.CreateModel(
            name='RecipientCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Categories of recipients')),
            ],
            options={
                'verbose_name': 'Recipient Category',
                'verbose_name_plural': 'Recipient Categories',
            },
        ),
        migrations.AddField(
            model_name='processingactivity',
            name='recipient_categories',
            field=models.ManyToManyField(to='vvt.RecipientCategory', verbose_name='Categories of recipients'),
        ),
        migrations.AddField(
            model_name='contact',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vvt.Department', verbose_name='Department'),
        ),
        migrations.RunPython(create_person_categories),
        migrations.RunPython(create_data_categories),
        migrations.RunPython(create_recipient_categories),
    ]
