# Generated by Django 2.0.5 on 2018-05-15 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vvt', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Verarbeitung',
            new_name='ProcessingActivity',
        ),
    ]
