# Generated by Django 2.0.5 on 2018-05-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vvt', '0002_auto_20180517_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingactivity',
            name='transfer',
            field=models.BooleanField(default=False, verbose_name='Transfer to third countries'),
        ),
        migrations.AlterField(
            model_name='processingactivity',
            name='transfer_recipient',
            field=models.TextField(blank=True, verbose_name='Transfer recipient'),
        ),
    ]
