# Generated by Django 2.0.5 on 2018-05-15 15:36

from django.db import migrations


def create_initial_contact(apps, schema_editor):
    Model = apps.get_model('vvt', 'Department')
    Model(name="NOCH OFFEN", pk=1).save()
    Model = apps.get_model('vvt', 'Contact')
    Model(name="NOCH OFFEN", department=1, pk=1).save()

def create_person_categories(apps, schema_editor):
    Model = apps.get_model('vvt', 'PersonCategory')
    Model(name="ALLE").save()
    Model(name="Mitarbeiter").save()
    Model(name="Lieferanten").save()
    Model(name="Kunden").save()
    Model(name="Interessenten").save()


def create_data_categories(apps, schema_editor):
    Model = apps.get_model('vvt', 'DataCategory')
    Model(name="ALLE").save()
    Model(name="Name").save()
    Model(name="Adressdaten").save()
    Model(name="Kontaktdaten").save()
    Model(name="Organisatorische Zuordnung").save()


def create_recipient_categories(apps, schema_editor):
    Model = apps.get_model('vvt', 'RecipientCategory')
    Model(name="KEINE").save()
    Model(name="Mitarbeiter").save()
    Model(name="Abteilungsleitung").save()
    Model(name="Geschäftsführung").save()
    Model(name="Konzernzentrale").save()
    Model(name="Fachbereich IT").save()
    Model(name="Fachbereich HR").save()
    Model(name="Fachbereich BR").save()
    Model(name="Geldinstitute ").save()
    Model(name="Finanzamt").save()
    Model(name="Krankenkassen").save()
    Model(name="Altersvorsorgeeinrichtungen").save()


class Migration(migrations.Migration):

    dependencies = [
        ('vvt', '0002_auto_20180515_1030'),
    ]

    operations = [
        migrations.RunPython(create_person_categories),
        migrations.RunPython(create_data_categories),
        migrations.RunPython(create_recipient_categories),
    ]
