# Generated by Django 2.0.5 on 2018-05-15 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vvt', '0003_auto_20180515_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Contact')),
                ('email', models.CharField(blank=True, max_length=50, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Phone')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Department')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.AlterModelOptions(
            name='datacategory',
            options={'verbose_name': 'Data Category', 'verbose_name_plural': 'Data Categories'},
        ),
        migrations.AlterModelOptions(
            name='personcategory',
            options={'verbose_name': 'Person Category', 'verbose_name_plural': 'Person Categories'},
        ),
        migrations.AlterModelOptions(
            name='processingactivity',
            options={'verbose_name': 'Processing Activity', 'verbose_name_plural': 'Processing Activities'},
        ),
        migrations.AlterModelOptions(
            name='recipientcategory',
            options={'verbose_name': 'Recipient Category', 'verbose_name_plural': 'Recipient Categories'},
        ),
        migrations.RemoveField(
            model_name='processingactivity',
            name='responsible',
        ),
        migrations.AddField(
            model_name='Kontakt',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vvt.Department', verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='processingactivity',
            name='contact',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vvt.Contact', verbose_name='Department'),
            preserve_default=False,
        ),
    ]
